### ISSUE TITLE
Interstitial Ad not closing

### ISSUE THREAD

**Issue by Mattijah** [googleads/swift-package-manager-google-mobile-ads#101]
I am using `GADInterstitialAd` and I see the delegate reporting `adDidRecordClick`, but the controller won't close and is still present even though the user tapped on it. Tapping on the close (X) button does however work.

Version: `11.8.0`
iOS: 17.5 & 15.5

**Comment by malandr2** [comment]
Hi @Mattijah, for us to properly triage your issue, please create a new thread in the [Admob developers forum](https://groups.google.com/g/google-admob-ads-sdk). Closing this out - thanks!

**Comment by Mattijah** [comment]
Ye, I have nothing better to do but create issues on 10 different portals
