### ISSUE TITLE
Close button displayed under status bar on iPhone 14 Pro with dynamic island

### ISSUE THREAD

**Issue by saschasalles** [googleads/swift-package-manager-google-mobile-ads#15]
Hello the Google Ads Team ! 

Unfortunately, some (not all) ads displayed on the new iPhone 14 Pro with the dynamic island have the close button stuck under the status bar. As a result, the user cannot close the ad and this makes the application completely inaccessible.
No error logs come up, even when overriding modalPresentationCapturesStatusBarAppearance.

Tested on iOS 16.0, with the latest release of Google Mobile Ads -> 9.11.0.
## Some examples: 
- [Screenshot 1](https://saschasalles.sirv.com/image.png)
- [Screenshot 2](https://saschasalles.sirv.com/IMG_0109.png)

I am looking for a solution very quickly, thank you very much in advance. 
Best regards,
Sascha Salles

**Comment by halilyilmaz** [comment]
Hi, 
I have same issue in my applications. I found one solution. It's not perfect but it works. 
You can hide status bar before show the ad and after when ad dismissed you can show status bar again. I can close ads like this.

if UIDevice.current.checkIfHasDynamicIsland() {
    UIApplication.shared.isStatusBarHidden = true
}

**Comment by malandr2** [comment]
Closing as this issue is not directly related to the swift-package-manager. If your issue still persists, please report your issue on the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk).
