### ISSUE TITLE
Library block update to Firebase 10.0.0

### ISSUE THREAD

**Issue by uniqby** [googleads/swift-package-manager-google-mobile-ads#19]
error project: Failed to resolve dependencies Dependencies could not be resolved because root depends on 'firebase-ios-sdk' 10.0.0..<11.0.0 and root depends on 'swift-package-manager-google-mobile-ads' 9.11.0..<10.0.0.
'swift-package-manager-google-mobile-ads' is incompatible with 'firebase-ios-sdk' because 'firebase-ios-sdk' 10.0.0 depends on 'googleappmeasurement' 10.0.0 and no versions of 'firebase-ios-sdk' match the requirement 10.0.1..<11.0.0.
'swift-package-manager-google-mobile-ads' >= 9.11.0 practically depends on 'googleappmeasurement' 7.0.0..<10.0.0 because 'swift-package-manager-google-mobile-ads' 9.11.0 depends on 'googleappmeasurement' 7.0.0..<10.0.0 and no versions of 'swift-package-manager-google-mobile-ads' match the requirement 9.11.1..<10.0.0.

**Comment by YurchukV** [comment]
Similar problem

**Comment by Koze** [comment]
@uniqby 
The dependencies of `swift-package-manager-google-mobile-ads` for `GoogleAppMeasurement` has changed in this commit. https://github.com/googleads/swift-package-manager-google-mobile-ads/commit/4d26ecbe79e7d435403baf76caef6c205153019b
You can use Firebase v10 with `swift-package-manager-google-mobile-ads` version 9.12.0 or later.

**Comment by malandr2** [comment]
Closing as due to inactivity and as we have updated the depenencies to the latest available compatible version. 

@uniqby if still an issue, see the comment from @Koze for a possible solution.
