### ISSUE TITLE
15 memory leaks (initialization)

### ISSUE THREAD

**Issue by Djibs** [googleads/swift-package-manager-google-mobile-ads#36]
Hello,

Using xcode's instrument to find memory leaks in my application, I found that I had 15 memory leaks. After searching, I found the problem: google Mobile Ads. If I deactivate Google mobile Ads.

To confirm this I created a new SwiftUI project with the simple text "hello Word". I initialized Google Mobile Ads in appDelegate ( in application(application:didFinishLaunchingWithOptions:), with GADMobileAds.sharedInstance().start(completionHandler: nil) that's it.

the memory leak problem is still present

![Capture ecran 2023-08-07 à 10 04 59](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/1236842/44f81011-ff29-4fd8-be38-c152650d398d)

Google Mobile Ads: 10.9
Xcode: 14.3.1
Simulator: iOS 16.4 on iPhone 14 Pro
macoOS: 13.5

Thank you

**Comment by Djibs** [comment]
Hello,

You just have to create a simple project in swiftUI and import google Mobile Ads.

You initialize google mobile ads in the AppDelagate class.

That's all.
The memory leaks are there without doing anything else

my project : https://github.com/Djibs/testMemoryLeaksGoogleMobileAdsv10.9/tree/main/testMemoryLeaksGoogleMobileAds

**Comment by malandr2** [comment]
Thanks,

This issue doesn't appear to be related to the Swift Package Manager and more so the SDK itself. Can you re-route your issue to the Google Mobile Ads SDK [Developer Forum](https://groups.google.com/g/google-admob-ads-sdk)? This will help resolve your issue. 

Thanks
