### ISSUE TITLE
Bug: GADMobileAds breaks the Global Setted AccentColor

### ISSUE THREAD

**Issue by muhasturk** [googleads/swift-package-manager-google-mobile-ads#38]
Implemented GoogleMobileAds with spm to my another Swift package. Calling `GADMobileAds.sharedInstance().start()` resets the accent color to default one.

To reproduce follow these steps.

- Integrate GADMobileAds into another Swift package.
- Add that package to iOS App target.
- Set AccentColor in Assets.xcassets
- Start GoogleMobileAds by following
```swift
GADMobileAds.sharedInstance().start()
```

You will see that the color you set in AccentColor is not working anymore. Commenting out `GADMobileAds.sharedInstance().start()` fixes the problem.

### Env
- Xcode 14.3.1
- swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

Can you investigate a solution?

**Comment by malandr2** [comment]
Hi @muhasturk, 

This issue doesn't appear to be related to the Swift Package Manager and more so the SDK itself. Can you re-route your issue to the Google Mobile Ads SDK [Developer Forum](https://groups.google.com/g/google-admob-ads-sdk)? This will help resolve your issue. When you create your case, please include a minimum reproducible sample to demonstrate your problem.

Thanks
