### ISSUE TITLE
Binary Target Inaccessible: 404 Bad Request

### ISSUE THREAD

**Issue by jfk056** [googleads/swift-package-manager-google-mobile-ads#44]
Since the morning we are experiencing the issue to access the binary target which is returning 404.

![Screenshot 2023-10-05 at 09 51 17](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/8448629/270eeb5f-5465-4551-8af7-901417554f95)

![Screenshot 2023-10-05 at 09 49 57](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/8448629/8e50939d-268e-4ea9-a001-12180df3a20c)

**Comment by KoichiroKAMADA** [comment]
+1

**Comment by michalnowak061** [comment]
same

**Comment by stodirascu** [comment]
+1

**Comment by keremerkan** [comment]
Sama. Going to the URL via browser confirms error 404 as well. Using range of versions setting in SPM with 10.0.0 < 10.12.0 as a workaround until this is fixed.

**Comment by houmie** [comment]
Yes, I used 10.11.0 and it worked as a workaround.

**Comment by ankit-thanekar007** [comment]
+1

**Comment by starchey** [comment]
+1

**Comment by malandr2** [comment]
HI all, 

Thanks for flagging. Please try again, the issue should no longer be 404ing.
