### ISSUE TITLE
Linker error: `duplicate symbol '_adView' in:` when using AppLovin 

### ISSUE THREAD

**Issue by stsandro** [googleads/swift-package-manager-google-mobile-ads#55]
I've encountered a linker error while utilizing the latest package version 11.0.0 alongside the mediation adapter and SDK for AppLovin. It appears that both SDKs contain a file named `OMIDJavaScriptSessionService.o` or `GADOMIDJavaScriptSessionService.o` with an _adView attribute (refer to the attached screenshot). This issue first surfaced with version 11.0.0; however, version 10.14.0 functions properly in this aspect.

<img width="1521" alt="Screenshot 2024-02-07 at 11 16 52" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/912599/3af186f8-6e5d-4f0d-8612-68c46885c16d">

**Comment by lotz** [comment]
Looks like 11.0.1 fixes this! Thanks for getting on it so quickly.

https://github.com/googleads/swift-package-manager-google-mobile-ads/releases/tag/11.0.1

**Comment by stsandro** [comment]
Yes, I just confirmed it. It is fixed now. 

Thanks you 🙏
