### ISSUE TITLE
Daily active users (DAU) Dropped 

### ISSUE THREAD

**Issue by jakirseu** [googleads/swift-package-manager-google-mobile-ads#61]
After updating to latest release, my app's Daily active users (DAU) dropped. I guess it's does not send DAU data to Admob. Revenue is okay.

**Comment by malandr2** [comment]
Hey @jakirseu, your query would be better suited for the [AdMob developers forum](https://groups.google.com/g/google-admob-ads-sdk). Please create a new thread there. Closing this out. Thanks!
