### ISSUE TITLE
Will not build with Xcode 15.3

### ISSUE THREAD

**Issue by sharpwestOFW** [googleads/swift-package-manager-google-mobile-ads#63]
![image](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/125922969/977e3438-3898-4035-ae6f-3623aa8da204)
When trying to install the app using this sdk version 11.0.1 we see this error in the screenshot above

**Comment by malandr2** [comment]
See https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62 for discussion
