### ISSUE TITLE
Issues after updating firebase-ios-sdk

### ISSUE THREAD

**Issue by frantischek** [googleads/swift-package-manager-google-mobile-ads#66]
I updated https://github.com/firebase/firebase-ios-sdk/ because of [issues/12441](https://github.com/firebase/firebase-ios-sdk/issues/12441), but now I get this error: Couldn't stat /Users//Library/Developer/CoreSimulator/Devices/****-****42B0-9841-/data/Library/Caches/com.apple.mobile.installd.staging/temp.aWbqKV/extracted/****/Frameworks/GoogleMobileAds.framework/Info.plist: No such file or directory

<img width="281" alt="grafik" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/6368507/5a5cf4e8-c852-429d-ad58-41f99a255c93">

**Comment by tehsven** [comment]
I believe this is a duplicate of https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62

**Comment by frantischek** [comment]
Thanks, @tehsven  - I will close this one.
