### ISSUE TITLE
Xcode 15.3 & iOS 17.4 app install issue: Framework is missing its bundle executable.

### ISSUE THREAD

**Issue by Clem23** [googleads/swift-package-manager-google-mobile-ads#69]
After updating Xcode to version 15.3, I can't install my app either on simulator or real device on iOS 17.4.

Here is the error message I got when installing (Build succeed):

> Please try again later. Framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path 'MyApp.app/Frameworks/GoogleMobileAds.framework/GoogleMobileAds'

<img width="461" alt="Capture d’écran 2024-03-18 à 21 02 53" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/4660073/d4ee1f0a-3a99-40f9-8bea-60d91797e42d">

I don't have any issue when deploying on iOS 17.0.1, 17.2 or 17.3 on both sim and device. Does anyone face the same issue?

**_Detail of the error:_**
```
Impossible d’installer « My App »
Domain: IXUserPresentableErrorDomain
Code: 1
Recovery Suggestion: My App.app/Frameworks/GoogleMobileAds.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "My App.app/Frameworks/GoogleMobileAds.framework/GoogleMobileAds".
User Info: {
    DVTErrorCreationDateKey = "2024-03-18 20:12:00 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
}
--
Impossible d’installer « My App »
Domain: IXUserPresentableErrorDomain
Code: 1
Recovery Suggestion: My App.app/Frameworks/GoogleMobileAds.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "My App.app/Frameworks/GoogleMobileAds.framework/GoogleMobileAds".
User Info: {
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
}
--
Failed to install the app on the device.
Domain: com.apple.dt.CoreDeviceError
Code: 3002
User Info: {
    NSURL = "file:///Users/clement/Library/Developer/Xcode/DerivedData/MyApp-dwgovybwoaicqghaqtvbngdkplip/Build/Products/Debug-iphoneos/My%20App.app/";
}
--
Impossible d’installer « My App »
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Réessayez ultérieurement.
Recovery Suggestion: My App.app/Frameworks/GoogleMobileAds.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "My App.app/Frameworks/GoogleMobileAds.framework/GoogleMobileAds".
--
My App.app/Frameworks/GoogleMobileAds.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "My App.app/Frameworks/GoogleMobileAds.framework/GoogleMobileAds".
Domain: MIInstallerErrorDomain
Code: 71
User Info: {
    FunctionName = "-[MIExecutableBundle executableExistsWithError:]";
    SourceFileLine = 1580;
}
--
lstat of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.cYcAbK/extracted/My App.app/Frameworks/GoogleMobileAds.framework/GoogleMobileAds failed: No such file or directory
Domain: NSPOSIXErrorDomain
Code: 2
Failure Reason: No such file or directory
User Info: {
    FunctionName = "-[MIFileManager itemExistsAtURL:error:]";
    SourceFileLine = 1340;
}
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_isWireless" = 1;
    "device_model" = "iPhone12,3";
    "device_osBuild" = "17.4 (21E219)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "355.24";
    "dvt_mobiledevice_version" = "1643.100.58";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 10200;
    "operation_errorCode" = 1;
    "operation_errorDomain" = IXUserPresentableErrorDomain;
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.4";
    "sdk_osVersion" = "17.4";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 14.0 (Build 23A344)
Xcode 15.3 (22618) (Build 15E204a)
Timestamp: 2024-03-18T21:12:00+01:00
```

**Comment by alancook** [comment]
Same problem the package does not install a info.plist in the build framework
![Screenshot 2024-03-19 at 1 35 32 PM](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/821098/e15d861e-0aaf-45ff-aebd-81c55cb36fba)

App installation failed: Unable To Install "App"
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/XXX/Library/Developer/CoreSimulator/Devices/ AAA/data/Library/Caches/com.
Invoicing. app/Frameworks/GoogleMobileAds.framework; Extra info about "/Users/XXX/Library/Developer/CoreSimulator/Devices/
BAM406E-4554-4985-A13E-9A6DEAACUdRALbrArchASCon-ADDIA.MobElAnsaoSdndEAmEA5L2RAXzACEAdA
Invoicing.app/Frameworks/GoogleMobileAds.framework/Info.plist";
Couldn't stat /Users/XXX/Library/Developer/CoreSimulator/
stalld.staging/tomp.L6bLz3/extracted/XXX
Invoicing-app/Frameworks/GoogleMobileAds.framework/Info.plist: No such file or directory
User Info: {
DVTErrorCreationDatoKey = "2024-03-19 04:25:42 +0000";
IDERunOperationFailingWorker = IDELaunchiPhoneSimulatorLauncher;
App installation failed: Unable To Install "XXX"
Domann.
Codes 1
Failure Reason: Ploase try again later
Recovery
Suggestion:
Failed to load Info.plist from bundle at path /Users/XXX/Library/Developer/CoreSimulator/Devices/
BA424D6F-15E4-4985-A13F-79A6D11EAAC3/data/Library/Caches/com.apple.mobile.installd.staaina/temp.L6bLz3/extracted/XXX
Invoicing-app/Frameworks/GoogloMobileAds.framework; Extra info about "/Users/XXX/Library/Developer/CoreSimulator/Devices/ BA424D6F-45E4-4085-A13-79A6D11EAAC3/data/Library/Caches/com.
temp. L6bLz3/extracted/XXX
Invoicing-app/Frameworks/GoogleMobileAds.framework/Info.plist": Couldn't stat /Users/XXX/Library/Developer/CoreSimulator/ Dovicos/BA42406F-45E-4085-A13F-79A6D11EAAC3/data/Library/Caches/com.apple.mobile.installd.staging/temp.LobLz3/extracted/XXX
Jat info: /Fameworks/GoogleMobilAdo. Framework/Info.Plist: No such filo or directory
IDERunOperationFailingWorker = IDELaunchiPhoneSimulatorLauncher;
SimcallingSelector
on66ne
Unable To Install "XXX"
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please
try again later.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/XXX/Library/Developer/CoreSimulator/Devices/ BA424D6F-454-4085-A13F-79A6D11EAAC3/data/Library/Caches/com.apple.mobile.installd.staging/temp.L6bLz3/extracted/XXX
info about "/Users/XXX/Library/Developer/CoreSimulator/Devices/
/Users/XXX/Library/Developer/CoreSimulator/
Devices/BA424D6F-454-4085-A13F-79A6D11EAAC3/data/Library/Caches/com.apple-mobile.installd.staging/temp.L6bLz3/extracted/XXX
Invoicing.app/Frameworks/GoogleMobileAds.framework/Info.plist: No such
ile or directory
Failed to load Info.plist from bundle at path /Users/XXX/Library Developer CoreSimulator/ Devices/BA424D6F-454-4085-A13F-79A6D11EAAC3/data/Library/Caches/com.apple.mobile.installd.staging/temp.L6bLz3/extracted/XXX Invoicing.app/Frameworks/ GoogleMobileAds. framework;
Extra
info about "/Users/XXX/Library/Developer/CoreSimulator/Devices/BA424D6F-45Е4-4085-
A13F-79A6011EAA03/data/Library/@aches/com.apple.mobile.installd.staaina/temp.L6bL73/extracted/XXX Invoicina.app/Erameworks/
A13F-79A6D11EAAC3/data/Library/Caches/com.apple.mobile.installd.staging/temp.L6bLz3/extracted/XXX Invoicing-app/Frameworks/
GoogleMobileAds. framework/Info.plist: No such file or directory
Domain: MTinstal LerErrorDomain
Coda: 25
User
Info: 1
FunctionName = "-[MIBundle _validateWithError:]";
LegacyErrOrString
SourceFileLine

**Comment by malandr2** [comment]
Hi @Clem23, I am unable to replicate running Xcode 15.3 running an iOS 17.4 simulator. 

Can you confirm your GMA (and UMP SDK) versions are 11.2.0 (and 2.3.0)?

<img width="350" alt="Screenshot 2024-03-19 at 5 26 26 PM" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/5905170/5934649a-fa43-45f5-98fe-1f6540784034">

**Comment by Clem23** [comment]
Yes I confirm! 
![Capture d’écran 2024-03-19 à 22 29 16](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/4660073/48cfd0b3-b515-4e4e-a3a7-ccdf6a3864ec)

**Comment by Clem23** [comment]
I have something interesting. Error seems to not be present when I build in release. The install error occurs only when building with debug scheme.

I will check what is different in the Build Settings and 'll try to identify what cause this issue.

**Comment by Clem23** [comment]
I find something!

I don't know why but the build setting "Skip App Store Deployment" was enabled for DEBUG configuration...
![Capture d’écran 2024-03-19 à 23 38 49](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/4660073/befa86f0-22a6-4c32-81eb-ee09ef34def3)

Changing it to "NO" fixed the issue.

Now I don't know if it should be considered as an issue or not but good to know for those who get same issue at least.

Clement

**Comment by talaviram** [comment]
Did you update the Admob SDK? are you using additional package to wrap AdMobs?

Due to nature of dependencies... Something is maybe cached or need explicit resolve.

I had similar issues  https://github.com/dearhui/AdmobSwiftUI/issues/3

**Comment by alancook** [comment]
Thanks update the package we can run our app again

**Comment by jesuslg123** [comment]
I am actually facing the same issue since few days and I block. For me no matter if release or debug mode, I can build but not deploy into any environment.

This is my current package set:
<img width="302" alt="image" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/7817064/6c25458c-443a-40d2-9045-3724079fc15f">

**Comment by jesuslg123** [comment]
Yes, I did. After many attempt I did updated the SDK to 11.2 and now seems solved. Sorry for the noise. 11.2 seems to fix the issue.

**Comment by malandr2** [comment]
Thanks all for the discussion. If anyone comes across this thread please update your Google Mobile Ads SDK to 11.2.0+ (and if necessary UMP SDK 2.3.0+)

**Comment by DorZafrir** [comment]
On Xcode 15.3 with version 11.2 I get this error now:
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JSContext", referenced from:
       in GoogleMobileAds[arm64][416](GADOMIDLightJSExecutor.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AT5HK** [comment]
> On Xcode 15.3 with version 11.2 I get this error now: ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found Undefined symbols for architecture arm64: "_OBJC_CLASS_$_JSContext", referenced from: in GoogleMobileAds[arm64][416](GADOMIDLightJSExecutor.o) ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have the same issue
