### ISSUE TITLE
NSPrivacyTracking and NSPrivacyTrackingDomains for Privacy Manifest

### ISSUE THREAD

**Issue by jfoulkes23** [googleads/swift-package-manager-google-mobile-ads#70]
I can see the in privacy manifest included in 11.2.0 there are no entries for `NSPrivacyTracking` or `NSPrivacyTrackingDomains`. Apple docs state:

```A Boolean that indicates whether your app or third-party SDK uses data for tracking as defined under the App Tracking Transparency framework. For more information, see [User Privacy and Data Use](https://developer.apple.com/app-store/user-privacy-and-data-use/).```

Since `NSPrivacyCollectedDataTypeDeviceID` is marked as true for `NSPrivacyCollectedDataTypeTracking` in the privacy manifest, should there be values for `NSPrivacyTracking` and `NSPrivacyTrackingDomains`. If not, do you have any guidance on how to handle this in a consuming app?

**Comment by malandr2** [comment]
Hey @jfoulkes23,

After including the updated GMA SDK v11.2.0+ which includes a Privacy Manifest in your app, no other action is required. For more information about the GMA SDK's data usage, please refer to our [developer documentation](https://developers.google.com/admob/ios/privacy/data-disclosure).
