### ISSUE TITLE
"Update to latest package version" in XCode stuck at 10.14.0

### ISSUE THREAD

**Issue by thereallee** [googleads/swift-package-manager-google-mobile-ads#71]
I cannot get it to update to 11.2.0 for instance.

XCode 15.3

**Comment by ericleich** [comment]
Version 11.0.0 requires compiling with iOS 12. https://github.com/googleads/swift-package-manager-google-mobile-ads/commit/65d389575d2628dc2ca6988557f2e86f67b971b9 updated the requirement. My guess is your configuration is for iOS 11 and therefore the latest compatible version is 10.14.0.

**Comment by thereallee** [comment]
Thanks for quick reply. Turns out that I had to update the Package Dependencies -> Dependency Rule in the project file.  I wasn't able to set it to 11 in SPM
