### ISSUE TITLE
Xcode 15.3 Version 11.2.0

### ISSUE THREAD

**Issue by DorZafrir** [googleads/swift-package-manager-google-mobile-ads#72]
I get this error when building on Xcode 15.3 With version 11.2.0

ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JSContext", referenced from:
       in GoogleMobileAds[arm64][416](GADOMIDLightJSExecutor.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by apxto** [comment]
same error...but didn't find any solution

**Comment by charlessnow** [comment]
same error

**Comment by apxto** [comment]
@DorZafrir @charlessnow i found a solution for my problem. Maybe it helps you too.

I had to add JavaScript Framework in Project Navigator under Build Phases -> Link Binaries with Libraries. Just try it out by add the JavaScript.framework.

Like this but with JavaScript Framework:
![image](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/85297002/f9424210-034a-4e82-bc54-ac25b0f90561)
