### ISSUE TITLE
AdMob request fails with ERROR_CODE_NETWORK_ERROR when ATT is set to Not Track

### ISSUE THREAD

**Issue by mrbodich** [googleads/swift-package-manager-google-mobile-ads#76]
When the App Tracking Transparency `Allow Tracking` setting for my app in set to Not Track (toggle is off), the AdMob request fails with the Error Code 2: ERROR_CODE_NETWORK_ERROR. It looks exactly like the iOS blocks endpoints listed in google-ads manifest file, while that completely brakes the Ads serving.

It happened right after I've updated the package version to the one with added Privacy Manifest.
It affects any our account and all test ads from docs.
Test ads only work in preview when I develop my package which importing google-mobile-ads package (when there is no Privacy Manifest impact). Once I switch to the iOS app I get all that Code 2 errors everywhere (preview, simulator, device) if ATT is disabled.

So, how to fix that and what is it?
1. A bug?
2. Not yet refactored endpoints by separating tracking endpoints to separate endpoints/domains and will be fixed soon?
3. Google officially says that Google Ads will not work anymore if ATT is disabled, eg for 70% of iOS users?

Have no idea how to deal with it from now...

**Comment by ericleich** [comment]
The privacy manifest in Google Mobile Ads SDK 11.3.0 does not declare privacy domains. Is there any chance your app's privacy manifest or some other library's manifest is including that domain?

**Comment by mrbodich** [comment]
Hi @ericleich . Thank you for the fast reply. You are absolutely right, I've tried to get rid of the problem when I can't pass the Points of Interest test (https://forums.developer.apple.com/forums/thread/744659), and added these domains to one of my submodules. Just forgot to remove because added in several places.
Thank you again, and sorry for the confusion!

**Comment by ericleich** [comment]
@mrbodich thanks for confirming. Happy to hear that's all it was.
