### ISSUE TITLE
XCode 14.3 and iOS 14 error on device install 

### ISSUE THREAD

**Issue by floriangbh** [googleads/swift-package-manager-google-mobile-ads#78]
Hello,

After upgrading the SDK to v11.3.0 I have this error on device install : 
`
Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.AsNjOr/extracted/Speedometer.app/Frameworks/UserMessagingPlatform.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.AsNjOr/extracted/Speedometer.app/Frameworks/UserMessagingPlatform.framework/Info.plist": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.AsNjOr/extracted/Speedometer.app/Frameworks/UserMessagingPlatform.framework/Info.plist: No such file or directory
`

I see in the v11.2.0 point `Updated the SDK's Info.plist to work around a Swift Package Manager issue on Xcode 15.3.`. Maybe the issue is still there ? 

Thanks

**Comment by RenNishino** [comment]
I ran into the same error

**Comment by malandr2** [comment]
Starting with [version 11.0.0](https://developers.google.com/admob/ios/rel-notes) we increased the minimum supported Xcode version to 15.1. Please follow-up if you're still seeing the error with the minimum support Xcode version

**Comment by floriangbh** [comment]
I made a mistake, I meant 15.3 and not 14.3. The error is present on Xcode 15.3

**Comment by floriangbh** [comment]
Same issue with another project
