### ISSUE TITLE
usermessagingplatform.framework does not support the minimum os version specified in the info.plist.

### ISSUE THREAD

**Issue by wlxo0401** [googleads/swift-package-manager-google-mobile-ads#79]
usermessagingplatform.framework does not support the minimum os version specified in the info.plist.

admob 11.3, 11.2

xcode: 15.3
mac: 14.4.1

**Comment by AT5HK** [comment]
how did you fix this issues. It seems to work fine for me in cocoapods but i get this error with SPM

**Comment by wlxo0401** [comment]
> how did you fix this issues. It seems to work fine for me in cocoapods but i get this error with SPM

<img width="460" alt="스크린샷 2024-05-12 오후 11 23 11" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/57979066/7add2d73-e3e6-4a34-9fbc-67bb990be3d4">

I also had a problem with SPM. 

I checked and found out that the AdMob I added was the latest version, but the AdMob's dependency libraries were not up to date. So I went ahead with the update. 

In my case the problem wasn't solved by deleting and reinstalling AdMob, 

I solved it through "Update to Latest Package Version" in the left menu of Xcode.
