### ISSUE TITLE
SPM xcode 15.4 Failed to load Info.plist  from UserMessagingPlatform.framework

### ISSUE THREAD

**Issue by motokotomax** [googleads/swift-package-manager-google-mobile-ads#81]
Hello,

After use SDK to v11.5.0 I have this error on device install :
Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.g44dBB/extracted/Control.app/Frameworks/UserMessagingPlatform.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.g44dBB/extracted/Control.app/Frameworks/UserMessagingPlatform.framework/Info.plist": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.g44dBB/extracted/Control.app/Frameworks/UserMessagingPlatform.framework/Info.plist: No such file or directory

try versions 11.0.0 - 11.5.0 - the same error
xcode 15.4, SPM
ios 17.5.1

could you please help

Thanks

**Comment by floriangbh** [comment]
Same issue here 

https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/78

**Comment by dr-star** [comment]
Is there any news on that?

**Comment by dr-star** [comment]
> Hello,
> 
> After use SDK to v11.5.0 I have this error on device install : Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.g44dBB/extracted/Control.app/Frameworks/UserMessagingPlatform.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.g44dBB/extracted/Control.app/Frameworks/UserMessagingPlatform.framework/Info.plist": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.g44dBB/extracted/Control.app/Frameworks/UserMessagingPlatform.framework/Info.plist: No such file or directory
> 
> try versions 11.0.0 - 11.5.0 - the same error xcode 15.4, SPM ios 17.5.1
> 
> could you please help
> 
> Thanks
Do you have the GoogleUserMessagingPlatform declared under "Frameworks, Libraries, and Embedded Content" ?
 
In my case, I added "https://github.com/googleads/swift-package-manager-google-user-messaging-platform" as a dependency and now it is working

**Comment by abear247** [comment]
Why do we need to add another SDK to make this one work though? This should not fail to run onto a device because of a dependency it requires. This is not really an acceptable workaround.
