### ISSUE TITLE
GAMBannerView appears truncated in UITableViewCell

### ISSUE THREAD

**Issue by rjourde** [googleads/swift-package-manager-google-mobile-ads#85]
I am displaying a UITableView containing various `UITableViewCell`. One of these cells includes a `GAMBannerView`. The `GAMBannerView` is added to the cell's contentView and constrained appropriately.

When the table view initially appears on the screen, the `GAMBannerView` appears truncated. Upon examining the size of the `GAMBannerView`'s frame within the `bannerViewDidReceiveAd` function of the `GADBannerViewDelegate`, the height is as expected (144).

<img width="345" alt="Capture d’écran 2024-06-17 à 08 51 54" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/1008617/e244a281-1695-4e51-843a-90c3e326dba6">

However, inspecting the view hierarchy reveals that the `WKCompositingView` is not at the correct height, being 171 instead.

<img width="586" alt="Capture d’écran 2024-06-17 à 09 27 26" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/1008617/32abab2c-33f6-43ff-8647-f2d14333d11d">

Are there any known issues with GAMBannerView and its initial rendering within a UITableViewCell?
Are there any recommended workarounds or fixes for ensuring the correct initial display of GAMBannerView?

Any insights or suggestions to resolve this behavior would be greatly appreciated.

**GAMBannerView configuration:**
* adSize: GADAdSizeFluid
* validAdSizes: [NSValueFromGADAdSize(GADAdSizeFluid)]

**Configuration:**
- GoogleMobileAds version 11.5.0
- Xcode 15.4.0
- iOS 17.5

**Comment by malandr2** [comment]
Hi @rjourde, 

@mr-fixit is correct, please create a new thread there (if you haven't already) for the your issue to be properly triaged. Closing this out. Thanks!
