### ISSUE TITLE
 Support for visionOS in GoogleMobileAds Framework

### ISSUE THREAD

**Issue by entaku0818** [googleads/swift-package-manager-google-mobile-ads#89]
Hello,

I am currently working on a project that includes support for visionOS. However, I encountered an issue when attempting to build the project with the GoogleMobileAds framework. The following error message is displayed:

```
/Users/entaku/Library/Developer/Xcode/DerivedData/VoiLog-chvljtffgmrjvffbxwkvqbhojpra/SourcePackages/artifacts/swift-package-manager-google-mobile-ads/GoogleMobileAds/GoogleMobileAds.xcframework:1:1 While building for visionOS, no library for this platform was found in '/Users/entaku/Library/Developer/Xcode/DerivedData/VoiLog-chvljtffgmrjvffbxwkvqbhojpra/SourcePackages/artifacts/swift-package-manager-google-mobile-ads/GoogleMobileAds/GoogleMobileAds.xcframework'.
```

**Steps to Reproduce:**
1. Integrate the GoogleMobileAds framework via Swift Package Manager.
2. Attempt to build the project for visionOS.

**Expected Behavior:**
The project should build successfully for visionOS, and the GoogleMobileAds framework should be compatible with visionOS.

**Actual Behavior:**
The build fails with the error mentioned above, indicating that no library for visionOS is found in the GoogleMobileAds.xcframework.

**Comment by malandr2** [comment]
Hi @entaku0818, please create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) to property track your request. 

Thanks! Closing this out.
