### ISSUE TITLE
Crash on M1 Mac

### ISSUE THREAD

**Issue by roceller** [googleads/swift-package-manager-google-mobile-ads#91]
Running on M1 Mac results in a crash. The older version runs fine.

Error:

`Failed to look up symbolic reference at 0x10129f809 - offset 559575 - symbol symbolic _____Sg 14MarketplaceKit14AppDistributorO in /private/var/folders/9t/_2ryztps0hlcmypnx2zz5vmh0000gn/X/020C087A-4EBE-52DB-8FA2-4C2A0ABEBC13/d/Wrapper/AppName.app/AppName`

Rolling back to version 10.14.0 resolves the issue.

**Comment by okiookio** [comment]
same on mine
M1 Pro + sonoma 14.5

rollback to 11.4.0 can fix but that not good.

> Failed to look up symbolic reference at 0x10548c0fb - offset 1328333 - symbol symbolic _____Sg 14MarketplaceKit14AppDistributorO in /private/var/folders/zr/vq0fzdzd7h72_kddt654l0zh0000gn/X

**Comment by MartinStrambach** [comment]
Any plans to fix this? Probably everyone who distributes iPad apps to arm macs is affected by this issue.

**Comment by iskand3rov** [comment]
++ works only when setting the exact version ~11.4.0

**Comment by malandr2** [comment]
Hi @all,

This issue has been resolved in [11.9.0](https://developers.google.com/admob/ios/rel-notes). Please update your Google Mobile Ads SDK to the latest version to see this change.
