### ISSUE TITLE
GADAppOpenAd fullScreenContentDelegate don't trigger events

### ISSUE THREAD

**Issue by skeduino** [googleads/swift-package-manager-google-mobile-ads#93]
Hello,

I'm trying to implement App open ads using [Google Admob example](https://developers.google.com/admob/ios/app-open) with test ads and latest SPM version (11.7.0) and iOS 17.5.1 and 17.2.1.
My issue is that `fullScreenContentDelegate` isn't calling `adDidDismissFullScreenContent ` after ad is dismissed. Also no error is received. 
The only callback method called is `adWillPresentFullScreenContent` when ad is starting to show.
Could you please check?

Thanks.

**Comment by malandr2** [comment]
Hi @skeduino, for us to properly triage this can you create a new thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk)? From there we can begin the troubleshooting process. Closing this out - thanks!
