### ISSUE TITLE
The SDK overrides the app's accent color (AccentColor) from the default asset catalog when using SwiftUI

### ISSUE THREAD

**Issue by coderExMachina** [googleads/swift-package-manager-google-mobile-ads#96]
The SDK overrides the app's accent color (AccentColor) from the default asset catalog when using SwiftUI.

**Comment by malandr2** [comment]
Hi @coderExMachina, for us to properly triage this can you create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk)? From there we can begin the troubleshooting process. We recommend to provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) as well. Closing this out as triaging will take place in the forum - thanks!
