### ISSUE TITLE
Google Mobile Ads SDK Causing Crash in iPad App Running on macOS (Mac Catalyst)

### ISSUE THREAD

**Issue by Charchoghlyan** [googleads/swift-package-manager-google-mobile-ads#97]
I am experiencing a crash in my iOS project when using the Google Mobile Ads SDK. The issue occurs specifically when running my iPad app on macOS (Mac Catalyst). Removing the Google Mobile Ads Swift Package Manager (SPM) dependency resolves the issue, but I need to continue using the SDK in my app on iOS/iPadOS.

Failed to look up symbolic reference at 0x1018991b1 - offset 754711 - symbol symbolic _____Sg 14MarketplaceKit14AppDistributorO in /private/var/folders/3p/**/*

**Comment by juanillo62gm** [comment]
Same issue here. This is what I found

- https://stackoverflow.com/questions/78808081/why-does-running-an-ios-app-through-macos-cause-failed-to-look-up-symbolic-refe

Setting package version to `11.5.0` works for me

**Comment by malandr2** [comment]
Hi @all,

This issue has been resolved in [11.9.0](https://developers.google.com/admob/ios/rel-notes). Please update your Google Mobile Ads SDK to the latest version to see this change.
