### ISSUE TITLE
App Open Ads doesn't take the full screen when another view is presented

### ISSUE THREAD

**Issue by sheikhbayazid** [googleads/swift-package-manager-google-mobile-ads#99]
# App Open Ad Doesn't Occupy the Full Screen When an Overlay View is Present

## Issue

When attempting to present an App Open Ad with a `nil` value for the root view controller, the ad does not occupy the full screen as expected.

**Example:**

```
appOpenAd.present(fromRootViewController: nil)
```

This issue occurs when another view, such as an overlay, is already being presented.

![IMG_9027](https://github.com/user-attachments/assets/63d6ebc2-3e83-4123-819a-2d42206d7115)

## Use Case

This problem is particularly evident when using In-App Messaging through OneSignal. If an In-App Message is displayed as an overlay and you attempt to present the App Open Ad simultaneously, the ad only occupies the area within the overlay instead of taking up the entire screen as intended.

## Currently Working Solution

Passing a specific view controller to the `present(fromRootViewController:)` method resolves this issue. The following code snippet demonstrates a workaround:

```swift
if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene {
    if let rootViewController = windowScene.windows.first?.rootViewController {
        appOpenAd.present(fromRootViewController: rootViewController)
    }
}
```

This ensures that the App Open Ad is presented over the entire screen, even when an overlay is present.

**Comment by malandr2** [comment]
Hi @sheikhbayazid, can you a create a new thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk)? This issue is related to the ad implementation which the Swift Package Manager doesn't control. From there our support team can begin the troubleshooting process

Closing this out - thanks!
